image:
  repository: 051826725870.dkr.ecr.eu-west-1.amazonaws.com/nestjs
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 3000
  nodePort: 32001

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80