image:
  repository: your-docker-registry/nodejs-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  name: node-app
  type: NodePort
  port: 3000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80