image:
  repository: ghcr.io/dadashussein/nodej
  pullPolicy: Always
  # Use a specific tag from your CI/CD pipeline (e.g., commit SHA, build number, or timestamp)
  # tag: latest  # Avoid using latest
  tag: "${VERSION}"  # This will be replaced by your CI/CD pipeline

service:
  type: NodePort
  port: 3000
  nodePort: 32001

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

imagePullSecrets:
  - name: github-container-registry
