name: Docker Image CI for GHHCR

on:
  push


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.SERVICE_ACCOUNT }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
  
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'
      - run: |
          helm upgrade --install nodejs-app ./nodejs-app --namespace github
          kubectl get all -n github