name: Docker Image CI for GHHCR

on:
  push


jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push theh image
        run: |
          docker login --username dadashussein  --password ${{secrets.GH_PAT}} ghcr.io
          docker build . --tag ghcr.io/dadashussein/nodejs:latest
          docker push ghcr.io/dadashussein/nodejs:latest
