name: Docker Image CI for GHHCR

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push theh image
        run: |
          docker login --username dadashussein  --password ${{secrets.GH_PAT}} ghcr.io
          docker build . --tag ghcr.io/dadashussein/nodejs:latest
          docker push ghcr.io/dadashussein/nodejs:latest

  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.SERVICE_ACCOUNT }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install nodejs-app ./nodejs-app \
            --namespace github \
            --set image.repository=ghcr.io/dadashussein/nodejs \
            --set image.tag=latest \
            --create-namespace
